### ISSUE TITLE
ValueError: cannot select an axis to squeeze out which has size not equal to one?

### ISSUE THREAD

**Issue by ibrahimLearning** [luyanger1799/Amazing-Semantic-Segmentation#13]
I am using BiSegNet and ResNet152, it was training before. But after removing some validation images and their corresponding labels, when I started again training it gives the following error:

> ValueError: cannot select an axis to squeeze out which has size not equal to one?

Is there any suggestion please?

**Comment by ayadav10491** [comment]
@ibrahimLearning Even I am facing the same issue mentioned by you. Were you able to solve? If so, can you give some suggestion. Thanks.

**Comment by ibrahimLearning** [comment]
> 
> 
> @ibrahimLearning Even I am facing the same issue mentioned by you. Were you able to solve? If so, can you give some suggestion. Thanks.

Please check train and test images and labels carefully, Maybe they are mixed!!!
