### ISSUE TITLE
你好，我想问一下，你用的GPU内存是多大的，我将batch_size调为1了内存还是不够，我用的RTX2080

### ISSUE THREAD

**Issue by 1054816178** [luyanger1799/Amazing-Semantic-Segmentation#2]

**Comment by luyanger1799** [comment]
8G的1080，用的什么模型？把输入尺寸弄小一点呢

**Comment by 1054816178** [comment]
我添加tf对gpu的分配参数后，你的数据能跑通了，但我在运行我自己的数据（将格式改的和你的数据集一样了）做二分类时，经常是跑几个epoch后，miou_loss就接近过0.5，然后就飙升到1.0，我运行了一下测试，前面几轮的模型还有分类结果，到后面30到50轮，预测就变成全白色了（我试了unet，segnet，fcn8s都是这样），我查了很久都没查到问题所在，你遇到过吗？

**Comment by luyanger1799** [comment]
> 我添加tf对gpu的分配参数后，你的数据能跑通了，但我在运行我自己的数据（将格式改的和你的数据集一样了）做二分类时，经常是跑几个epoch后，miou_loss就接近过0.5，然后就飙升到1.0，我运行了一下测试，前面几轮的模型还有分类结果，到后面30到50轮，预测就变成全白色了（我试了unet，segnet，fcn8s都是这样），我查了很久都没查到问题所在，你遇到过吗？

你数据集多大啊，Miou_loss我没实际用过，你试试别的loss呢

**Comment by 1054816178** [comment]
我的数据集大概8000张，其他的loss，我按照你的要求输过，但训练时每一步显示依旧和原来一样显示的是MOIU_LOSS

**Comment by luyanger1799** [comment]
> 我的数据集大概8000张，其他的loss，我按照你的要求输过，但训练时每一步显示依旧和原来一样显示的是MOIU_LOSS

我下午看看，电脑正在跑着程序呢

**Comment by 1054816178** [comment]
好的，谢了

**Comment by luyanger1799** [comment]
我试了一下，在我这里没有出现类似的问题。。。

**Comment by 1054816178** [comment]
8G



---原始邮件---
发件人: "Yang Lu"<notifications@github.com&gt;
发送时间: 2019年10月26日(星期六) 下午2:00
收件人: "luyanger1799/Amazing-Semantic-Segmentation"<Amazing-Semantic-Segmentation@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"1054816178"<jiang_yif@qq.com&gt;;
主题: Re: [luyanger1799/Amazing-Semantic-Segmentation] 你好，我想问一下，你用的GPU内存是多大的，我将batch_size调为1了内存还是不够，我用的RTX2080 (#2)



我试了一下，在我这里没有出现类似的问题。。。

**Comment by 1054816178** [comment]
你好，能加一下qq吗？

**Comment by 1054816178** [comment]
输入python train.py --model UNet --base_model VGG16 --dataset data4 --loss CE --num_classes 2

 1/2368 [..............................] - ETA: 4:24:12 - loss: 181966.0000 - mean_io_u: 0.25212019-10-26 14:48:25.997342: I tensorflow/core/platform/default/device_tracer.cc:641] Collecting 1348 kernel records, 17 memcpy records.
2368/2368 [==============================] - 466s 197ms/step - loss: 125897.9069 - mean_io_u: 0.4768 - val_loss: 113406.0285 - val_mean_io_u: 1.0000
Epoch 2/15
2368/2368 [==============================] - 454s 192ms/step - loss: 92132.0486 - mean_io_u: 1.0000 - val_loss: 86606.4519 - val_mean_io_u: 1.0000
Epoch 3/15
2368/2368 [==============================] - 452s 191ms/step - loss: 69872.1541 - mean_io_u: 1.0000 - val_loss: 66412.7822 - val_mean_io_u: 1.0000
Epoch 4/15
2368/2368 [==============================] - 460s 194ms/step - loss: 55299.6013 - mean_io_u: 1.0000 - val_loss: 54367.2560 - val_mean_io_u: 1.0000
Epoch 5/15
2368/2368 [==============================] - 448s 189ms/step - loss: 46113.4520 - mean_io_u: 1.0000 - val_loss: 46894.8000 - val_mean_io_u: 1.0000

**Comment by luyanger1799** [comment]
给我发几张你的训练图像和标注图像

**Comment by 1054816178** [comment]
发你邮箱了

**Comment by luyanger1799** [comment]
从你的标注数据上看背景是0，前景应该是255，你应该把它处理成背景0，前景1。
比如你是k个类别，默认的标注顺序是0，1，2，...， k-1

**Comment by 1054816178** [comment]
哦，是这样，我去试试，非常感谢！

**Comment by luyanger1799** [comment]
有问题的话再反馈～

**Comment by 1054816178** [comment]
嗯

**Comment by swjtulinxi** [comment]
博主，你的这个loss为什么都是上千上万，和其他的loss不一样啊

**Comment by luyanger1799** [comment]
我是算的loss和，那些小的是算的均值，这个没影响的

**Comment by swjtulinxi** [comment]
还有就是你的这个metrics当中的MeanIOU，它老是提醒我keras.metrics has no attribute ‘ MeanIOU’中没这个模块，请问你知道怎么回事

**Comment by luyanger1799** [comment]
使用1.14以上的Tensorflow

**Comment by swjtulinxi** [comment]
我是用的1.14

**Comment by swjtulinxi** [comment]
还有用你的predict.py文件也提示
![image](https://user-images.githubusercontent.com/50089266/70386200-c8721380-19d1-11ea-9bfc-2e0f6c38f32d.png)

**Comment by luyanger1799** [comment]
你查看一下tensor flow api，看看1.14的有没有这个函数，没有的话升级到1.15吧，我平时都用2.0，是没什么问题的

**Comment by swjtulinxi** [comment]
1.15里面是有的吗，还有就是testt时也提示

  File "D:\anaconda\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py", line 619, in ndim
    dims = x.get_shape()._dims

AttributeError: 'function' object has no attribute 'get_shape'

**Comment by luyanger1799** [comment]
训练过程正常吗

**Comment by swjtulinxi** [comment]
正常，我只是把MeanIOU换成了自带的accuracy，

**Comment by luyanger1799** [comment]
你先试试1.15或者2.0行不行吧，要是还有问题的话我周三再检查一下，周二之前我得准备答辩，抽不出时间

**Comment by swjtulinxi** [comment]
好的，感谢

**Comment by swjtulinxi** [comment]
博主，我还有个问题就是你的文件里面还有个layer.py，里面还有globalaveragepooling2D和concatenate，这不是keras里面自带有的吗，为什么你还要写在这里

**Comment by luyanger1799** [comment]
keras里面的在个别模型上用不了，比如GlobalAveragePooling2D，keras里面的会改变纬度，但是个别模型上面要求纬度不变，Concatenate一样的道理，因为有的模型需要，所以重写了一下

**Comment by swjtulinxi** [comment]
他的功能是一样的吧，我还没遇到你说的情况，我把你的代码改成了tensorflow1.5版本，也能跑通没用你的layer.py，除了MeanIOU不能调用等。

**Comment by luyanger1799** [comment]
那是你没用到那个模型，你试试PSPNet和DenseASPP，你换了就跑不通了

**Comment by swjtulinxi** [comment]
可以呀，我就是用的denseaspp

**Comment by luyanger1799** [comment]
好吧，我写的时候是这个问题的。。。不过都一样，官方的能用也行，都是在官方代码基础上改的

**Comment by swjtulinxi** [comment]
还有就是如果你能写个预测一张大图的代码就更完美了，而不是只能预测模型训练时的图片大小

**Comment by luyanger1799** [comment]
等过段时间吧，最近忙毕业，好久没更新了

**Comment by swjtulinxi** [comment]
博主，这是我将你的代码改成tensorflow1.5的和完全用你的代码训练出来的结果，我改的那个除了xuexilv方案没用你的以外，其他都用的基本是你的代码效果如下：
![image](https://user-images.githubusercontent.com/50089266/70389840-c7f07180-19ff-11ea-9a34-fad747587791.png)
中间那个是我改后代码跑的，后面那个完全是用你的代码跑的，效果差别好大，不知道为什么

**Comment by luyanger1799** [comment]
图片我加载不出来，你单独发我邮箱吧

**Comment by swjtulinxi** [comment]
博主，你平常也用这个代码跑吗?那你跑过像voc2012和cityscape这类的数据集吗，你的效果怎样，问什么我用你这个代码跑出来的meaniou都很低，效果也一般，就是达不到论文的效果，请问你又遇到这样的情况吗？
博主，还有个问题就是你的评估.py那个代码，我用了你的代码运行查看miou值，然后又在网上找了几个版本的精度评定代码，算出来的miou值都和你的代码结果不一样，我不知道该相信哪个版本，麻烦你查看一下是否有误，非常感谢

**Comment by swjtulinxi** [comment]
> 哦，是这样，我去试试，非常感谢！
你好，请问下你用这个代码做出来的效果怎样，好不好？

**Comment by swjtulinxi** [comment]
博主，我终于发现问题所在了，我是用的val做测试，在训练时val_mean_iou=0.59，用你的test.py得出的lmeaniou=0.65，用你的evaluate.py的出的meaniou=0.55，问题出在计算meaniou值部分，不晓得哪个部分是对的，哪个是错的，请检查一下，我研究这个问题几天了

**Comment by lyc1995452-star** [comment]
> 博主，我终于发现问题所在了，我是用的val做测试，在训练时val_mean_iou=0.59，用你的test.py得出的lmeaniou=0.65，用你的evaluate.py的出的meaniou=0.55，问题出在计算meaniou值部分，不晓得哪个部分是对的，哪个是错的，请检查一下，我研究这个问题几天了

请问你跑了deeplabv3+这个网络结构没有，效果如何呢？

**Comment by luyanger1799** [comment]
不好意思，我现在不做这方向了，所以代码没怎么维护，具体的你研究一下吧。test.py和evaluate.py不一致的原因应该是计算方式的差异，你查一下别人是怎么计算的，自己写一个评估一下就好了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyc1995452-star"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 下午3:44
收件人:&nbsp;"luyanger1799/Amazing-Semantic-Segmentation"<Amazing-Semantic-Segmentation@noreply.github.com&gt;;
抄送:&nbsp;"Yang"<luyanger1799@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [luyanger1799/Amazing-Semantic-Segmentation] 你好，我想问一下，你用的GPU内存是多大的，我将batch_size调为1了内存还是不够，我用的RTX2080 (#2)





  
博主，我终于发现问题所在了，我是用的val做测试，在训练时val_mean_iou=0.59，用你的test.py得出的lmeaniou=0.65，用你的evaluate.py的出的meaniou=0.55，问题出在计算meaniou值部分，不晓得哪个部分是对的，哪个是错的，请检查一下，我研究这个问题几天了
  
请问你跑了deeplabv3+这个网络结构没有，效果如何呢？

**Comment by lyc1995452-star** [comment]
博主当初有没有添加空洞卷积在deeplabv3+里面，你有测试那个模型效果最好吗？

**Comment by luyanger1799** [comment]
v3+是有空洞卷积的呀，模型效果，因为我处理的数据类型跟常见的数据差异比较大，没有参考价值------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;lyc1995452-star&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月23日(星期二) 下午3:59
收件人:&nbsp;&quot;luyanger1799/Amazing-Semantic-Segmentation&quot;<Amazing-Semantic-Segmentation@noreply.github.com&gt;;
抄送:&nbsp;&quot;Yang Lu&quot;<luyanger1799@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [luyanger1799/Amazing-Semantic-Segmentation] 你好，我想问一下，你用的GPU内存是多大的，我将batch_size调为1了内存还是不够，我用的RTX2080 (#2)

**Comment by lyc1995452-star** [comment]
博主，我在运行predict.py AttributeError: 'Namespace' object has no attribute 'color_csv',我有把class_dict.csv添加到数据下了啊，请问这是什么情况。

**Comment by luyanger1799** [comment]
> 博主，我在运行predict.py AttributeError: 'Namespace' object has no attribute 'color_csv',我有把class_dict.csv添加到数据下了啊，请问这是什么情况。

已解决
