### ISSUE TITLE
The output path for model weights after training

### ISSUE THREAD

**Issue by mrkind** [luyanger1799/Amazing-Semantic-Segmentation#8]
Is there any checkpoints so that I can stop training when I wish.

What is the output path of checkpoints or final model weights?

**Comment by csracing01** [comment]
Path for checkpoints: Amazing-Semantic-Segmentation/checkpoints/
Path for model weights: Amazing-Semantic-Segmentation/weights/

**Comment by mrkind** [comment]
good!
